### ISSUE TITLE
minimum y axis height. 

### ISSUE THREAD

**Issue by rjangid1** [elmarquez/angular-metrics-graphics#6]
the default height of y axis is decided by the maximum value in the series. 
in case all the values in the series are zero, Y axis disappears. Is there a way to specify a minimum default height ?

chart options are 

```
$scope.chartOptions =
            title: 'Metric Trend'
            x_accessor: 'date'
            y_accessor: 'value'
            area: false
            small_text: true
            right: 40    
            aggregate_rollover: false
```

<img width="561" alt="screen shot 2016-03-22 at 10 13 23 am" src="https://cloud.githubusercontent.com/assets/10449098/13942289/c0ed2e9e-f016-11e5-9f2d-2cc35a44ee96.png">

**Comment by elmarquez** [comment]
Try adding a height property. For example:

`$scope.chartOptions = {
  ...
  height: 200
}`

**Comment by rjangid1** [comment]
Hi,
I tried setting height but doesn't seem to be working. attached screenshot. 

<img width="917" alt="screen shot 2016-04-12 at 10 23 36 am" src="https://cloud.githubusercontent.com/assets/10449098/14450124/bf6caea4-0098-11e6-84fe-8b82f8be87e9.png">
