### ISSUE TITLE
multichart line starting points

### ISSUE THREAD

**Issue by rjangid1** [elmarquez/angular-metrics-graphics#7]
I'm using multiline charts in my angular application and noticed that the starting point is sometimes inconsistent. 

chart options are

```
$scope.chartOptions =
            title: '',
            x_accessor: 'date'
            y_accessor: 'value'
            small_text: true
            legend: []
            legend_target: '.legend'
            area: false,
            aggregate_rollover: false
            full_width: true
```

<img width="1294" alt="screen shot 2016-03-15 at 7 05 52 pm" src="https://cloud.githubusercontent.com/assets/10449098/13942505/1102e516-f019-11e5-9f82-630655b39259.png">

**Comment by elmarquez** [comment]
This is likely a MetricsGraphics issue but I'm happy to look at it anyway. Can you post some sample data so that I can take a look at this?
